language: bash
services: docker
before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
before_script:
- ./update.sh
- GHOST_VERSION=`git ls-remote --tags https://github.com/TryGhost/Ghost.git | cut -d$'\t' -f2 | grep -E '^refs/tags/[0-9]+\.[0-9]+' | cut -d/ -f3 | cut -d^ -f1 | sort -ruV | head -1`
script:
- docker build 3/debian/ -t alparaschiv/ghost-docker-node:$GHOST_VERSION
- docker build 3/alpine/ -t alparaschiv/ghost-docker-node:$GHOST_VERSION-alpine
- docker tag alparaschiv/ghost-docker-node:$GHOST_VERSION alparaschiv/ghost-docker-node:latest
after_script:
- docker images
- docker push alparaschiv/ghost-docker-node:$GHOST_VERSION-alpine
- docker push alparaschiv/ghost-docker-node:$GHOST_VERSION
- docker push alparaschiv/ghost-docker-node:latest
